api_platform:
    title: Amsterdam Martial Arts API Platform
    description: API for martial arts school
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    messenger:
        enabled: true
        # jsonapi:  ['application/vnd.api+json']
    # docs_formats:
    #     jsonld: ['application/ld+json']
    #     jsonopenapi: ['application/vnd.openapi+json']
    # http_cache:
    #     invalidation:
            # We assume that your API can reach your caddy instance by the hostname http://caddy.
            # The endpoint /souin-api/souin is the default path to the invalidation API.
            # urls: [ 'http://caddy/souin-api/souin' ]
            # purger: api_platform.http_cache.purger.souin
    # defaults:
    #     stateless: true
    #     cache_headers:
    #         vary: ['Content-Type', 'X-Authorization', 'Origin']
    #     extra_properties:
    #         standard_put: false
    #         rfc_7807_compliant_errors: true
    # keep_legacy_inflector: false
    use_symfony_listeners: true
    eager_loading:
        enabled: false
        # max_joins: 100
        # force_eager: false
    swagger:
         api_keys:
             access_token:
                name: Authorization
                type: header
