framework:
  webhook:
    routing:
      MollieDirectPayment:
        service: App\Webhook\MollieDirectPaymentRequestParser
        secret: your_secret_here
      MollieSubscriptionPayment:
        service: App\Webhook\MollieSubscriptionPaymentRequestParser
        secret: your_secret_here
