<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240627141813 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("do $$
        BEGIN 
            perform table_name FROM information_schema.tables
            WHERE table_name='product_vat';
                IF NOT FOUND THEN
                    CREATE TABLE product_vat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vat_amount NUMERIC(17, 2) NOT NULL, vat_rate_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY(id));
                    CREATE INDEX IDX_649C762C43897540 ON product_vat (vat_rate_id);
                    CREATE INDEX IDX_649C762C4584665A ON product_vat (product_id);
                    ALTER TABLE product_vat ADD CONSTRAINT FK_649C762C43897540 FOREIGN KEY (vat_rate_id) REFERENCES vat_rate (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
                    ALTER TABLE product_vat ADD CONSTRAINT FK_649C762C4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
                END IF;
        END;
        $$ language PLPGSQL"
        );
        // $this->addSql('CREATE TABLE product_vat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vat_amount NUMERIC(17, 2) NOT NULL, vat_rate_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY(id))');
        // $this->addSql('CREATE INDEX IDX_649C762C43897540 ON product_vat (vat_rate_id)');
        // $this->addSql('CREATE INDEX IDX_649C762C4584665A ON product_vat (product_id)');
        // $this->addSql('ALTER TABLE product_vat ADD CONSTRAINT FK_649C762C43897540 FOREIGN KEY (vat_rate_id) REFERENCES vat_rate (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        // $this->addSql('ALTER TABLE product_vat ADD CONSTRAINT FK_649C762C4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE product_vat DROP CONSTRAINT FK_649C762C43897540');
        $this->addSql('ALTER TABLE product_vat DROP CONSTRAINT FK_649C762C4584665A');
        $this->addSql('DROP TABLE product_vat');
    }
}
