<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240627211956 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
    //     $this->addSql("do $$
    //     BEGIN 
    //         perform table_name FROM information_schema.tables
    //         WHERE table_name='order_line';
    //             IF NOT FOUND THEN
    //                 CREATE TABLE order_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price NUMERIC(17, 2) NOT NULL, qty INT NOT NULL, shop_order_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY(id));
    //                 CREATE INDEX IDX_9CE58EE1562797AE ON order_line (shop_order_id);
    //                 CREATE INDEX IDX_9CE58EE14584665A ON order_line (product_id);
    //                 ALTER TABLE order_line ADD CONSTRAINT FK_9CE58EE1562797AE FOREIGN KEY (shop_order_id) REFERENCES shop_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
    //                 ALTER TABLE order_line ADD CONSTRAINT FK_9CE58EE14584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
    //             END IF;
    //     END;
    //     $$ language PLPGSQL"
    // );
        // ALTER TABLE shop_order ADD order_status_id INT NOT NULL;
        // ALTER TABLE shop_order ADD CONSTRAINT FK_323FC9CAD7707B45 FOREIGN KEY (order_status_id) REFERENCES order_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
        // CREATE INDEX IDX_323FC9CAD7707B45 ON shop_order (order_status_id);

        $this->addSql('CREATE TABLE IF NOT EXISTS order_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price NUMERIC(17, 2) NOT NULL, qty INT NOT NULL, shop_order_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_9CE58EE1562797AE ON order_line (shop_order_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_9CE58EE14584665A ON order_line (product_id)');
        // $this->addSql('ALTER TABLE order_line ADD IF NOT EXISTS CONSTRAINT FK_9CE58EE1562797AE FOREIGN KEY (shop_order_id) REFERENCES shop_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_line DROP CONSTRAINT IF EXISTS FK_9CE58EE1562797AE');
        $this->addSql('ALTER TABLE order_line ADD CONSTRAINT FK_9CE58EE1562797AE FOREIGN KEY (shop_order_id) REFERENCES shop_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // $this->addSql('ALTER TABLE order_line ADD IF NOT EXISTS CONSTRAINT FK_9CE58EE14584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_line DROP CONSTRAINT IF EXISTS FK_9CE58EE14584665A');
        $this->addSql('ALTER TABLE order_line ADD CONSTRAINT FK_9CE58EE14584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');


        // $this->addSql('ALTER TABLE  IF NOT EXISTS shop_order ADD order_status_id INT NOT NULL');
        // $this->addSql('ALTER TABLE  IF NOT EXISTS shop_order ADD CONSTRAINT FK_323FC9CAD7707B45 FOREIGN KEY (order_status_id) REFERENCES order_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        // $this->addSql('CREATE  IF NOT EXISTS INDEX IDX_323FC9CAD7707B45 ON shop_order (order_status_id)');
    }
        // $this->addSql('ALTER TABLE subscription DROP CONSTRAINT IF EXISTS FK_A3C664D3636ACC40');
        // $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3636ACC40 FOREIGN KEY

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE order_line DROP CONSTRAINT FK_9CE58EE1562797AE');
        $this->addSql('ALTER TABLE order_line DROP CONSTRAINT FK_9CE58EE14584665A');
        $this->addSql('DROP TABLE order_line');
        $this->addSql('ALTER TABLE shop_order DROP CONSTRAINT FK_323FC9CAD7707B45');
        $this->addSql('DROP INDEX IDX_323FC9CAD7707B45');
        $this->addSql('ALTER TABLE shop_order DROP order_status_id');
    }
}
