<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240601115059 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE IF NOT EXISTS "group" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, code INT NOT NULL, PRIMARY KEY(id))');
        // $this->addSql('CREATE TABLE IF NOT EXISTS post_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(50) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql("do $$
        BEGIN 
            perform table_name FROM information_schema.tables
            WHERE table_name='user_profile';
                IF NOT FOUND THEN
                    ALTER TABLE user_profile ADD group_student_id INT DEFAULT NULL;
                    ALTER TABLE user_profile ADD CONSTRAINT FK_D95AB4051C592EA8 FOREIGN KEY (group_student_id) REFERENCES \"group\" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
                    CREATE INDEX IDX_D95AB4051C592EA8 ON user_profile (group_student_id);
                END IF;
        END;
        $$ language PLPGSQL");
        // $this->addSql('ALTER TABLE user_profile ADD group_student_id INT DEFAULT NULL');
        // $this->addSql('ALTER TABLE user_profile ADD CONSTRAINT FK_D95AB4051C592EA8 FOREIGN KEY (group_student_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        // $this->addSql('CREATE INDEX IDX_D95AB4051C592EA8 ON user_profile (group_student_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE "group"');
        $this->addSql('ALTER TABLE user_profile DROP CONSTRAINT FK_D95AB4051C592EA8');
        $this->addSql('DROP INDEX IDX_D95AB4051C592EA8');
        $this->addSql('ALTER TABLE user_profile DROP group_student_id');
    }
}
