<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240602180405 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE IF NOT EXISTS post_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(50) NOT NULL, description VARCHAR(255) DEFAULT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, related_user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql("do $$
        BEGIN 
            perform conrelid::regclass AS table_name, conname AS foreignKey, pg_get_constraintdef(oid) 
            FROM pg_constraint 
            WHERE contype = 'f' AND connamespace = 'public'::regnamespace AND pg_get_constraintdef(oid) LIKE '%related_user_id%';
                IF NOT FOUND THEN
                    CREATE INDEX IDX_ACB5864898771930 ON post_event (related_user_id);
                    ALTER TABLE post_event ADD CONSTRAINT FK_ACB5864898771930 FOREIGN KEY (related_user_id) REFERENCES user_profile (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
                    CREATE INDEX IDX_D95AB4051C592EA8 ON user_profile (group_student_id);
                END IF;
        END;
        $$ language PLPGSQL");
        // $this->addSql('CREATE INDEX IDX_ACB5864898771930 ON post_event (related_user_id)');
        // $this->addSql('ALTER TABLE post_event ADD CONSTRAINT FK_ACB5864898771930 FOREIGN KEY (related_user_id) REFERENCES user_profile (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE post_event DROP CONSTRAINT FK_ACB5864898771930');
        $this->addSql('DROP TABLE post_event');
    }
}
