<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240624190007 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("do $$
        BEGIN 
            perform table_name FROM information_schema.tables
            WHERE table_name='product';
                IF NOT FOUND THEN
                    CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, price NUMERIC(17, 2) NOT NULL, description VARCHAR(510) NOT NULL, images TEXT DEFAULT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT NOT NULL, currency_id INT NOT NULL, duration_id INT NOT NULL, PRIMARY KEY(id));
                    CREATE INDEX IDX_D34A04AD9777D11E ON product (category_id);
                    CREATE INDEX IDX_D34A04AD28A69C31 ON product (currency_id)'
                    CREATE INDEX IDX_D34A04AD23A4A42B ON product (duration_id);
                    ALTER TABLE product ADD CONSTRAINT FK_D34A04AD9777D11E FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE
                    ALTER TABLE product ADD CONSTRAINT FK_D34A04AD28A69C31 FOREIGN KEY (currency_id) REFERENCES currency_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE
                    ALTER TABLE product ADD CONSTRAINT FK_D34A04AD23A4A42B FOREIGN KEY (duration_id) REFERENCES subscription_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE
                END IF;
        END;
        $$ language PLPGSQL"
        );
        // $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, price NUMERIC(17, 2) NOT NULL, description VARCHAR(510) NOT NULL, images TEXT DEFAULT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT NOT NULL, currency_id INT NOT NULL, duration_id INT NOT NULL, PRIMARY KEY(id))');
        // $this->addSql('CREATE INDEX IDX_D34A04AD9777D11E ON product (category_id)');
        // $this->addSql('CREATE INDEX IDX_D34A04AD28A69C31 ON product (currency_id)');
        // $this->addSql('CREATE INDEX IDX_D34A04AD23A4A42B ON product (duration_id)');
        // $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD9777D11E FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        // $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD28A69C31 FOREIGN KEY (currency_id) REFERENCES currency_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        // $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD23A4A42B FOREIGN KEY (duration_id) REFERENCES subscription_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD9777D11E');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD28A69C31');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD23A4A42B');
        $this->addSql('DROP TABLE product');        
    }
}
