<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240627203523 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'create table shop order';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
    //     $this->addSql("do $$
    //     BEGIN 
    //         perform table_name FROM information_schema.tables
    //         WHERE table_name='shop_order';
    //             IF NOT FOUND THEN
    //                 CREATE TABLE shop_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_amount NUMERIC(17, 2) NOT NULL, order_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_owned_by_id INT NOT NULL, shipping_address_id INT DEFAULT NULL, order_status_id VARCHAR(15) DEFAULT NULL, PRIMARY KEY(id));
    //                 CREATE INDEX IDX_323FC9CA5E70BCD7 ON shop_order (order_owned_by_id);
    //                 CREATE INDEX IDX_323FC9CA4D4CFF2B ON shop_order (shipping_address_id);
    //                 ALTER TABLE shop_order ADD CONSTRAINT FK_323FC9CA5E70BCD7 FOREIGN KEY (order_owned_by_id) REFERENCES \"user\" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
    //                 ALTER TABLE shop_order ADD CONSTRAINT FK_323FC9CA4D4CFF2B FOREIGN KEY (shipping_address_id) REFERENCES user_address (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
    //             END IF;
    //     END;
    //     $$ language PLPGSQL"
    // );
        $this->addSql('CREATE TABLE IF NOT EXISTS shop_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_amount NUMERIC(17, 2) NOT NULL, order_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_owned_by_id INT NOT NULL, shipping_address_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_323FC9CA5E70BCD7 ON shop_order (order_owned_by_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_323FC9CA4D4CFF2B ON shop_order (shipping_address_id)');
        $this->addSql('ALTER TABLE shop_order DROP CONSTRAINT IF EXISTS FK_323FC9CA5E70BCD7');
        $this->addSql('ALTER TABLE shop_order ADD CONSTRAINT FK_323FC9CA5E70BCD7 FOREIGN KEY (order_owned_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE shop_order DROP CONSTRAINT IF EXISTS FK_323FC9CA4D4CFF2B');
        $this->addSql('ALTER TABLE shop_order ADD CONSTRAINT FK_323FC9CA4D4CFF2B FOREIGN KEY (shipping_address_id) REFERENCES user_address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE shop_order DROP CONSTRAINT FK_323FC9CA5E70BCD7');
        $this->addSql('ALTER TABLE shop_order DROP CONSTRAINT FK_323FC9CA4D4CFF2B');
        $this->addSql('DROP TABLE shop_order');
    }
}
