<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240627185116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'create table address';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS address (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unit_number VARCHAR(15) DEFAULT NULL, street_number INT NOT NULL, address_line VARCHAR(100) NOT NULL, city VARCHAR(100) NOT NULL, region VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(15) NOT NULL, country VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE address DROP CONSTRAINT FK_D4E6F81F92F3E70');
        $this->addSql('DROP TABLE address');
    }
}
