<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240627211956 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'create table order lines';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE order_line IF NOT EXISTS (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price NUMERIC(17, 2) NOT NULL, qty INT NOT NULL, shop_order_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_9CE58EE1562797AE ON order_line (shop_order_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_9CE58EE14584665A ON order_line (product_id)');
        $this->addSql('ALTER TABLE order_line DROP CONSTRAINT IF EXISTS FK_9CE58EE1562797AE');
        $this->addSql('ALTER TABLE order_line ADD CONSTRAINT FK_9CE58EE1562797AE FOREIGN KEY (shop_order_id) REFERENCES shop_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE order_line DROP CONSTRAINT IF EXISTS FK_9CE58EE14584665A');
        $this->addSql('ALTER TABLE order_line ADD CONSTRAINT FK_9CE58EE14584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
        
    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE order_line DROP CONSTRAINT FK_9CE58EE1562797AE');
        $this->addSql('ALTER TABLE order_line DROP CONSTRAINT FK_9CE58EE14584665A');
        $this->addSql('DROP TABLE order_line');
        $this->addSql('ALTER TABLE shop_order DROP CONSTRAINT FK_323FC9CAD7707B45');
        $this->addSql('DROP INDEX IDX_323FC9CAD7707B45');
        $this->addSql('ALTER TABLE shop_order DROP order_status_id');
    }
}
