<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240927134704 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE IF NOT EXISTS token_manager (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, tokens INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_profile_id INT NOT NULL, related_subscription_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_142B3C3A6B9DD454 ON token_manager (user_profile_id)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_142B3C3A1770D2F5 ON token_manager (related_subscription_id)');
        $this->addSql('ALTER TABLE token_manager DROP CONSTRAINT IF EXISTS FK_142B3C3A6B9DD454');
        $this->addSql('ALTER TABLE token_manager ADD CONSTRAINT FK_142B3C3A6B9DD454 FOREIGN KEY (user_profile_id) REFERENCES user_profile (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE token_manager DROP CONSTRAINT IF EXISTS FK_142B3C3A1770D2F5');
        $this->addSql('ALTER TABLE token_manager ADD CONSTRAINT FK_142B3C3A1770D2F5 FOREIGN KEY (related_subscription_id) REFERENCES subscription (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE token_manager DROP CONSTRAINT FK_142B3C3A6B9DD454');
        $this->addSql('ALTER TABLE token_manager DROP CONSTRAINT FK_142B3C3A1770D2F5');
        $this->addSql('DROP TABLE token_manager');
    }
}
