<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240627190347 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'create table user address';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
    //     $this->addSql("do $$
    //     BEGIN 
    //         perform table_name FROM information_schema.tables
    //         WHERE table_name='user_address';
    //             IF NOT FOUND THEN
    //                 CREATE TABLE user_address (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_default BOOLEAN NOT NULL, related_user_id INT NOT NULL, address_id INT NOT NULL, PRIMARY KEY(id));
    //                 CREATE INDEX IDX_5543718B98771930 ON user_address (related_user_id);
    //                 CREATE INDEX IDX_5543718BF5B7AF75 ON user_address (address_id);
    //                 ALTER TABLE user_address ADD CONSTRAINT FK_5543718B98771930 FOREIGN KEY (related_user_id) REFERENCES \"user\" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
    //                 ALTER TABLE user_address ADD CONSTRAINT FK_5543718BF5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
    //             END IF;
    //     END;
    //     $$ language PLPGSQL"
    // );
    $this->addSql('CREATE TABLE user_address IF NOT EXIST (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_default BOOLEAN NOT NULL, related_user_id INT NOT NULL, address_id INT NOT NULL, PRIMARY KEY(id))');
    $this->addSql('CREATE INDEX IF NOT EXISTS IDX_5543718B98771930 ON user_address (related_user_id)');
    $this->addSql('CREATE INDEX IF NOT EXISTS IDX_5543718BF5B7AF75 ON user_address (address_id)');
    $this->addSql('ALTER TABLE user_address DROP CONSTRAINT FK_5543718B98771930');
    $this->addSql('ALTER TABLE user_address ADD CONSTRAINT FK_5543718B98771930 FOREIGN KEY (related_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE user_address DROP CONSTRAINT FK_5543718BF5B7AF75');
    $this->addSql('ALTER TABLE user_address ADD CONSTRAINT FK_5543718BF5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE user_address DROP CONSTRAINT FK_5543718B98771930');
        $this->addSql('ALTER TABLE user_address DROP CONSTRAINT FK_5543718BF5B7AF75');
        $this->addSql('DROP TABLE user_address');
    }
}
