<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240816033216 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE status_transfer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, transfer_id VARCHAR(22) NOT NULL, status VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DDEE0418FCDAEAAA ON status_transfer (order_id)');
        $this->addSql('ALTER TABLE status_transfer ADD CONSTRAINT FK_DDEE0418FCDAEAAA FOREIGN KEY (order_id) REFERENCES shop_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE status_transfer DROP CONSTRAINT FK_DDEE0418FCDAEAAA');
        $this->addSql('DROP TABLE status_transfer');
    }
}
