# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mollie.live: '%env(MOLLIE_LIVE_KEY)%'
    mollie.test: '%env(MOLLIE_TEST_KEY)%'
    mollie.key: '%env(MOLLIE_WEBHOOK_SECRET)%'
    'string $apiTestKey': '%mollie.test%'
    'string $apiLiveKey': '%mollie.live%'

when@dev:
    parameters:
        mollie.live: '%env(MOLLIE_LIVE_KEY)%'
        mollie.test: '%env(MOLLIE_TEST_KEY)%'
        mollie.key: '%env(MOLLIE_WEBHOOK_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind: 
            $eventSubscriptionLogger: '@monolog.logger.M.A.Event'
            $transferEventLogger: '@monolog.logger.TransferEvent'
            $subscriptionEventLogger: '@monolog.logger.SubscriptionEvent'

    

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            # - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\ExceptionListener:
        tags:
            - { 
                name:   kernel.event_listener,
                event:  kernel.exception
            }

    Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\JWTAuthenticator:
        autowire: true

    App\Service\MollieApiService:
        # bind:
        #     $apiTestKey: '%mollie.test%'
        #     $apiLiveKey: '%mollie.live%'
    
    Mollie\Api\MollieApiClient:
        autowire: true
            
    #api platform service
    # app.product.search_filter:
    #     parent:         'api_platform.doctrine.orm.search_filter'
    #     arguments:      [ { duration: ~ } ]
    #     tags:           [{name: 'api_platform.filter' }]
    
    # app.user.search_filter:
    #     parent:         'api_platform.doctrine.orm.search_filter'
    #     arguments:      [{ id: 'exact' , subscriptions.transferId: 'exact'}]
    #     # arguments:      [{ id: 'exact' , subscriptions.status: 'exact'}]
    #     tags:           [{ name: 'api_platform.filter'}]
    #     autowire:       false # required, explained below
    #     autoconfigure:  false # required, explained below
    #     public:         false

    # app.user.property_filter:
    #     parent:         'api_platform.serializer.property_filter'
    #     tags:           [{name: 'api_platform.filter'}]
    #     autowire:       false # required, explained below
    #     autoconfigure:  false # required, explained below
    #     public:         false
    
    # app.subscription.property_filter:
    #     parent:     'api_platform.doctrine.orm.search_filter'
    #     # parent: 'api_platform.serializer.property_filter'
    #     arguments:  [ { status: 'exact' } ]
    #     tags:       [{name: 'api_platform.filter'} ]

    # offer.order_filter:
    #     parent: 'api_platform.doctrine.orm.order_filter'
    #     arguments:
    #         $properties: { id: ~, firstName: ~ }
    #         $orderParameterName: order
    #     tags: ['api_platform.filter']
    
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines.
        # autowire: false
        # autoconfigure: false
        # public: false

    acme_api.event.jwt_created_listener: #set additional data JWT token
        class: App\EventListener\JWTCreatedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    App\http_kernel\cors_subscriber:
        class: App\EventSubscriber\HttpKernel\CorsSubscriber
        tags:
            - { name: kernel.event_subscriber }            

    App\http_kernel\Authorization_subscriber: #delete this
        class: App\EventSubscriber\HttpKernel\AuthorizationSubscriber
        tags:
            - { name: kernel.event_subscriber }
    
    App\http_kernel\forgot_password_event_subscriber:
        class: App\EventSubscriber\ForgotPasswordEventSubscriber
        tags:
            - { name: kernel.event_subscriber }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    acme_api.encoder.nixilla_jwt_encoder:
        class: App\Encoder\NixillaJWTEncoder
        
    App\Security\ApiKeyAuthenticator:
        class: App\Security\ApiKeyAuthenticator
        autowire: true

    app.custom_authenticator:
        class: App\Security\CustomAuthenticator
        parent: lexik_jwt_authentication.security.jwt_authenticator

    api_request_param_converter:
        class: App\ApiBundle\Utilities\ApiRequestParamConverter
        tags:
            - { name: request.param_converter }

    # this is the service's id
    # site_update_manager.superadmin:
    #     class: Symfony\Component\Uid\Factory\UuidFactory
    #     # you CAN still use autowiring: we just want to show what it looks like without
    #     # autowire: false
    #     # manually wire all arguments
    #     arguments:
    #         - '@App\Service\MessageGenerator'
    #         - '@mailer'
    #         - 'superadmin@example.com'

    # site_update_manager.normal_users:
    #     class: App\Service\SiteUpdateManager
    #     autowire: false
    #     arguments:
    #         - '@App\Service\MessageGenerator'
    #         - '@mailer'
    #         - 'contact@example.com'
    
    # CoopTilleuls\ForgotPasswordBundle\Provider\ProviderChainInterface:
        # class: CoopTilleuls\ForgotPasswordBundle\Provider\ProviderChainInterface
    
    CoopTilleuls\ForgotPasswordBundle\Manager\ForgotPasswordManager:
        class: CoopTilleuls\ForgotPasswordBundle\Manager\ForgotPasswordManager
        arguments:
            $passwordTokenManager: '@coop_tilleuls_forgot_password.manager.password_token'
            $providerChain: '@coop_tilleuls_forgot_password.provider_chain'
            # $manager: '@coop_tilleuls_forgot_password.manager.doctrine'
            # $userClass: App\Entity\user

    
    coop_tilleuls_forgot_password.controller.update_password:
        class: CoopTilleuls\ForgotPasswordBundle\Controller\UpdatePassword
        # arguments:
            # $forgotPasswordManager: '@coop_tilleuls_forgot_password.controller.update_password'
        tags: ['controller.service_arguments']
        
    # coop_tilleuls_forgot_password.create_token:insta
    #     class: CoopTilleuls\ForgotPasswordBundle\Event\CreateToken
    #     tags: ['controller.service_arguments']