# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mollie.live: '%env(MOLLIE_LIVE_KEY)%'
    mollie.test: '%env(MOLLIE_TEST_KEY)%'
    mollie.key: '%env(MOLLIE_WEBHOOK_SECRET)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind: 
            $eventSubscriptionLogger: '@monolog.logger.M.A.Event'
            $transferEventLogger: '@monolog.logger.TransferEvent'


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            # - '../src/Entity/'
            - '../src/Kernel.php'
    App\http_kernel\cors_subscriber:
        class: App\EventSubscriber\HttpKernel\CorsSubscriber
        tags:
            - { name: kernel.event_subscriber }
    
    App\http_kernel\forgot_password_event_subscriber:
        class: App\EventSubscriber\ForgotPasswordEventSubscriber
        tags:
            - { name: kernel.event_subscriber }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    acme_api.encoder.nixilla_jwt_encoder:
        class: App\Encoder\NixillaJWTEncoder
        
    App\Security\ApiKeyAuthenticator:
        class: App\Security\ApiKeyAuthenticator
        autowire: true

    app.custom_authenticator:
        class: App\Security\CustomAuthenticator
        parent: lexik_jwt_authentication.security.jwt_authenticator

    api_request_param_converter:
        class: App\ApiBundle\Utilities\ApiRequestParamConverter
        tags:
            - { name: request.param_converter }
    
    # CoopTilleuls\ForgotPasswordBundle\Provider\ProviderChainInterface:
        # class: CoopTilleuls\ForgotPasswordBundle\Provider\ProviderChainInterface
    
    CoopTilleuls\ForgotPasswordBundle\Manager\ForgotPasswordManager:
        class: CoopTilleuls\ForgotPasswordBundle\Manager\ForgotPasswordManager
        arguments:
            $passwordTokenManager: '@coop_tilleuls_forgot_password.manager.password_token'
            $providerChain: '@coop_tilleuls_forgot_password.provider_chain'
            # $manager: '@coop_tilleuls_forgot_password.manager.doctrine'
            # $userClass: App\Entity\user

    
    coop_tilleuls_forgot_password.controller.update_password:
        class: CoopTilleuls\ForgotPasswordBundle\Controller\UpdatePassword
        # arguments:
            # $forgotPasswordManager: '@coop_tilleuls_forgot_password.controller.update_password'
        tags: ['controller.service_arguments']
        
    # coop_tilleuls_forgot_password.create_token:insta
    #     class: CoopTilleuls\ForgotPasswordBundle\Event\CreateToken
    #     tags: ['controller.service_arguments']